package com.example.shopper;

import android.content.Intent;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.AdapterView;
import android.widget.ListView;

public class MainActivity extends AppCompatActivity {
    // declare an intent to start new activities
    Intent intent;

    // declare a database hanlder
    DBHandler dbHandler;

    // declare a Shopping Lists Cursor Adapter
    ShoppingLists shoppingListsAdpter;

    // declare a ListView
    ListView shopperListView;
    /**
     * This method initializes the Action bar and the view of the
     * Main activity
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        // this code generated by Android Studio initializes
        // the view and action bar of the Main activity
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        // initialize the database handler
        dbHandler= new DBHandler(this,null);
        // initialize the list view
        shopperListView=(ListView) findViewById(R.id.shopperListView);

        // initialize the shopping list Cursor adapter
        shoppingListsAdpter = new ShoppingLists(this, dbHandler.getShoppingLists(), 0);

        // set  shopping list Cursor adapter on ListView
        shopperListView.setAdapter(shoppingListsAdpter);

        // set OnItemClickListener to shopper ListView
        shopperListView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long id) {
                // launching The View List Activity and sending it the if of the
                // shopping list

                intent = new Intent(MainActivity.this, ViewList.class);
                intent.putExtra("_id", id);
                startActivity(intent);

            }
        });


    }


    /**
     * This method further initializes the Action bar of the Main activity. I
     * It gets the code we wrote in the menu  main and incorporates into the Action Bar
     * @param menu
     * @return
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    /**
     * This method gets called when an item in the overflow menu is selected and it controls
     * what happens when the item is selected
     * @param item item selected in the overflow men. It contains information about the item  for example, its id.
     * @return true if an item was selected; else it returns false.
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // get the id of the item that was selected
        switch(item.getItemId()){
            case R.id.action_home:
                // initializing an intent for the main activity, starting it
                // and returning true
                intent= new Intent(this,MainActivity.class);
                startActivity(intent);
                return true;

            case R.id.action_create_list:
                // initializing an intent for the create list activity, starting it
                // and returning true
                intent= new Intent (this, CreateList.class);
                startActivity(intent);
                return true;
                default:
                    return super.onOptionsItemSelected(item);


        }

    }

    public void openCreateList(View view) {
        // initializing an intent for the create list activity, starting it
        intent= new Intent (this, CreateList.class);
        startActivity(intent);

    }


}
